### ISSUE TITLE
Cannot be used perfectly on windows11 22H2

### ISSUE THREAD

**Issue by ghost** [Tatsu-syo/noMeiryoUI#52]
There is a problem with this version
No problems found in other versions
windows 22H2

when i change the font
### 1. Select the "Apply and Exit" question
Description: Will stay for an exceptionally long time. And cannot be turned off.
It can only be solved by logging out/restarting the system

### 2. Open some programs or there is a problem within a certain period of time
This is in ###1. Wait too long to restart and run it again to see the operation after the modification is successful.
Description: The interface appears blank (basically all programs) the mouse is seriously misplaced
It can only be solved by logging out/restarting the system

**Comment by Tatsu-syo** [comment]
# What is occured.

## 1. Select the "Apply and Exit" question

Partly, it's by design.
In early version when select "Apply and Exit", some software block exit.
This is why, "Apply and Exit" set settings separate thread, and exit after 5 seconds.

## 2. Open some programs or there is a problem within a certain period of time

This is same reason.
Some software can't handle system font change while running.
If you know such program, kill process and restart.
If you can't know program which can't handle handle system font change, you can only logging out or restarting the system.

## 3.Why on Windows 22H2?

I think newer program which can't handle handle system font change increased.

## 4.What I will do?

Prepare test version to aboid problem in Windows 11 22H2 and when official released, test and fix ploblems or add warning.
And in distribution page, write warnings.

This is my plan.
